###
POST http://localhost:9000/oauth2/token
Authorization: Basic messaging-client secret
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials

###
POST http://localhost:9000/oauth2/introspect
Authorization: Basic messaging-client secret
Content-Type: application/x-www-form-urlencoded

token=eyJraWQiOiI0ZmY2MjYxOC1mZGYxLTQ2YzgtOTNkMC0yODU2YmQ3NjBjOWEiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXNzYWdpbmctY2xpZW50IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTczNzcxNzI4OCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo5MDAwIiwiZXhwIjoxNzM3NzE3ODg4LCJpYXQiOjE3Mzc3MTcyODgsImp0aSI6ImFjMDU5YmRlLTlhMjgtNDIyZC04YjE0LTc2MjM0M2ZjNTEzMyJ9.T9jM7d8pLN2Buj-PKFHl0o2qK5T-AdNYfyciR_z-oeqlE2Uwkg5jgiOuPddErBMbr6024WNvwLWwjzaMrVTVALgG2Q8NKod7my2qXfh6fl6lhiy0afBXCYJiYyA4YNX8XxjqF_TM7rzme7ce9UBmLk1HIqE3gUU3FgTT-5KvsNmQaVKQ0Os8hrbidX8jeVnjF_Zx2CQvDcCU-OawvhqJaOr7ikRZ9bztWlYXL-afvjHFNi5NfDK5AupjMm2tMPIdTP49yn18O3CZUQWM5_3DiJwOdJ9R1Sb2bfha9WenkWGfj3pmVgqtrIq9DQXulufrND2giaEAXYcEFjt-S0McwQ
    &token_type_hint=access_token
