###
POST http://localhost:9000/oauth2/token
Authorization: Basic messaging-client secret
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials

###
POST http://localhost:9000/oauth2/introspect
Authorization: Basic messaging-client secret
Content-Type: application/x-www-form-urlencoded

token={{$auth.token("auth-id")}}&token_type_hint=access_token

###
GET http://localhost:9000/.well-known/openid-configuration
Authorization: Basic messaging-client secret
Content-Type: application/x-www-form-urlencoded


